/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gugumin.tim;

import com.gugumin.tim.pojo.Config;
import com.gugumin.tim.service.ImageService;
import com.gugumin.tim.utils.ValidUtil;

import java.nio.file.Path;
import java.util.List;

/**
 * The type App.
 *
 * @author minmin
 */
public class App {

    /**
     * The entry point of application.
     *
     * @param args the input arguments
     */
    public static void main(String[] args) {
        Config config = Config.load();
        List<Path> pathList = ValidUtil.checkPath(args);
        try (ImageService imageService = new ImageService()) {
            String result = imageService.postImage(config, pathList);
            System.out.println(result);
        }
    }
}
